image: Visual Studio 2017
configuration: Release

skip_branch_with_pr: true
branches:
  only:
    - master

version: 2.1.0.{build}

pull_requests:
  do_not_increment_build_number: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
- nuget restore

build:
  publish_nuget: true

deploy:
- provider: NuGet
  api_key:
    secure: lUmSV95QwsQtvPkHT02PT5fswmVcW0oMIJvOGEincUNnUNtTe3DOIjVEOpC0CMkQ
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
